FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --force --no-audit --no-fund

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run bot:build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev --force --no-audit --no-fund
COPY --from=builder /app/dist ./dist
CMD ["node", "dist/bot/bot/reddit-worker.js"]
