import type { Metadata } from "next";
import { PolicyPage } from "@/components/compliance/PolicyPage";

export const metadata: Metadata = { title: "Open-source Notices", description: "Code licensing and corresponding-source information for DEETNUTS and vendored eJAM components.", alternates: { canonical: "/compliance/open-source-notices" } };

export default function OpenSourceNotices() {
  const sourceCommit = process.env.VERCEL_GIT_COMMIT_SHA || process.env.NEXT_PUBLIC_SOURCE_COMMIT;
  return <PolicyPage title="Open-source notices" summary="Code licences are stated separately from third-party data, names, marks, fonts and assets."><section><h2>DEETNUTS code</h2><p>Original DEETNUTS software covered by the repository root licence is available under the MIT License, copyright 2024 Kewonit.</p></section><section><h2>eJAM</h2><p>The predictor interface and supporting data tooling are adapted from <a href="https://github.com/su6u/ejam">eJAM by su6u</a>, licensed AGPL-3.0-or-later. Its bundled <code>LICENSE</code> and <code>NOTICE</code> remain in the <code>ejam</code> directory; the notice excludes official datasets from the code licence.</p></section><section><h2>Source for this version</h2>{sourceCommit ? <p>The exact deployed source is <a href={`https://github.com/kewonit/deetnuts/tree/${sourceCommit}`}>commit {sourceCommit}</a>.</p> : <p>No immutable production commit identifier is available in this local build. Production deployment must set <code>VERCEL_GIT_COMMIT_SHA</code> or <code>NEXT_PUBLIC_SOURCE_COMMIT</code> and publish that exact corresponding source before release.</p>}</section><section><h2>Fonts and assets</h2><p>JEE cutoff pages use local system font stacks and make no remote font request. Third-party icons, names, logos and other assets retain their owners’ terms. A JEE-specific asset without established provenance must not be shipped.</p></section><section><h2>Data is not covered</h2><p>Neither MIT nor AGPL grants reuse rights in JoSAA, CSAB, NTA or institutional records. See <a href="/compliance/data-sources-and-licensing">data sources and licensing</a> for the current unconfirmed rights status.</p></section></PolicyPage>;
}
