upstream pocketbase_api {
    zone pocketbase_api 64k;
    server pocketbase:8090 resolve;
    keepalive 16;
}

upstream access_verifier {
    zone access_verifier 64k;
    server access-verifier:8081 resolve;
    keepalive 8;
}
