export const COURSE_GROUPS = {
  "Computer Science & IT": [
    "Computer Engineering",
    "Computer Science",
    "Computer Science and Engineering",
    "Computer Science and Business Systems",
    "Computer Science and Design",
    "Computer Science and Information Technology",
    "Computer Science and Technology",
    "Computer Technology",
    "Information Technology",
    "Electronics and Computer Engineering",
    "Electronics and Computer Science",
    "Computer Engineering (Software Engineering)",
  ],
  "AI & Data Science": [
    "Artificial Intelligence",
    "Artificial Intelligence (AI) and Data Science",
    "Artificial Intelligence and Data Science",
    "Artificial Intelligence and Machine Learning",
    "Computer Science and Engineering (Artificial Intelligence)",
    "Computer Science and Engineering (Artificial Intelligence and Data Science)",
    "Computer Science and Engineering(Artificial Intelligence and Machine Learning)",
    "Computer Science and Engineering(Data Science)",
    "Data Engineering",
    "Data Science",
    "Robotics and Artificial Intelligence",
  ],
  "Cybersecurity & IoT": [
    "Cyber Security",
    "Computer Science and Engineering (Cyber Security)",
    "Computer Science and Engineering (Internet of Things and Cyber Security Including Block Chain Technology)",
    "Computer Science and Engineering (IoT)",
    "Computer Science and Engineering(Cyber Security)",
    "Internet of Things (IoT)",
    "Industrial IoT",
  ],
  "Electronics & Communication": [
    "Electronics Engineering",
    "Electronics Engineering ( VLSI Design and Technology)",
    "Electronics and Biomedical Engineering",
    "Electronics and Communication Engineering",
    "Electronics and Communication (Advanced Communication Technology)",
    "Electronics and Communication(Advanced Communication Technology)",
    "Electronics and Telecommunication Engg",
    "VLSI",
  ],
  "Electrical Engineering": [
    "Electrical Engineering",
    "Electrical Engg[Electronics and Power]",
    "Electrical and Computer Engineering",
    "Electrical and Electronics Engineering",
    "Electrical, Electronics and Power",
  ],
  "Mechanical Engineering": [
    "Mechanical Engineering",
    "Mechanical Engineering Automobile",
    "Mechanical Engineering[Sandwich]",
    "Mechanical & Automation Engineering",
    "Mechanical and Mechatronics Engineering (Additive Manufacturing)",
    "Production Engineering",
    "Production Engineering[Sandwich]",
    "Manufacturing Science and Engineering",
  ],
  "Civil & Environmental": [
    "Civil Engineering",
    "Civil Engineering and Planning",
    "Civil and Environmental Engineering",
    "Civil and infrastructure Engineering",
    "Structural Engineering",
  ],
  "Chemical & Process": [
    "Chemical Engineering",
    "Petro Chemical Engineering",
    "Oil Technology",
    "Oil Fats and Waxes Technology",
    "Oil and Paints Technology",
    "Oil,Oleochemicals and Surfactants Technology",
    "Pharmaceutical and Fine Chemical Technology",
    "Pharmaceuticals Chemistry and Technology",
  ],
  "Biotechnology & Food": [
    "Bio Technology",
    "Bio Medical Engineering",
    "Food Engineering and Technology",
    "Food Technology",
    "Food Technology And Management",
  ],
  "Textile & Materials": [
    "Textile Engineering / Technology",
    "Textile Technology",
    "Textile Chemistry",
    "Technical Textiles",
    "Fibres and Textile Processing Technology",
    "Man Made Textile Technology",
    "Fashion Technology",
    "Plastic Technology",
    "Plastic and Polymer Engineering",
    "Polymer Engineering and Technology",
    "Metallurgy and Material Technology",
  ],
  "Automation & Robotics": [
    "Automation and Robotics",
    "Mechatronics Engineering",
    "Robotics and Automation",
    "Instrumentation Engineering",
    "Instrumentation and Control Engineering",
  ],
  "Specialized Engineering": [
    "Aeronautical Engineering",
    "Agricultural Engineering",
    "Automobile Engineering",
    "Mining Engineering",
    "Fire Engineering",
    "Safety and Fire Engineering",
    "Dyestuff Technology",
    "Paints Technology",
    "Surface Coating Technology",
    "Paper and Pulp Technology",
    "Printing and Packing Technology",
    "Architectural Assistantship",
  ],
  "Emerging Technologies": ["5G"],
};

export type CourseGroupLabel = keyof typeof COURSE_GROUPS;
